### ISSUE TITLE
[Proposal] Archive 4.2 to a separate branch (linked and considered a first-class citizen) and make master deal with 5.1

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/IlluminateNonLaravel#13]
Illuminate/Laravel 5.1 is LTS, so it's the perfect candidate for the next step of this project; 4.3+ rely more heavily on HttpFoundation and middleware than 4.2 and before had, which is why this project has paused at 4.2 for now.

I think it's time, and have been encouraged in this direction by friends, to pursue a 5.1 version of this that is comfortable with explicitly requiring HTTPFoundation.

**Comment by mattstauffer** [comment]
First steps are on me. I'll need to do the move of the 4.2 work to another branch.

Then I'll set up a new foundation where each feature has its own unique `composer.json`.

I'll set up a more robust documentation framework.

And I'll do the first component as a sample. Then I'll ask for help to do the rest.

**Comment by freekmurze** [comment]
Great initiative, I'll try to help where I can!
